### 1. 회원가입
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password123!",
  "name": "관리자 다다",
  "role": "ADMIN",
  "status": "ACTIVE"
}

### 1. 회원가입
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "email": "manager@test.com",
  "password": "password123",
  "name": "테스트 매니저"
}

### 2. 로그인 (성공 시 아래 변수에 토큰 복사)
# @name login
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "manager@test.com",
  "password": "password123"
}


### 3. 토큰 재발급
POST http://localhost:4000/api/auth/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWwxcDZ2OHAwMDAxdWM0NDhqM2MyNm1iIiwicm9sZSI6Ik1BTkFHRVIiLCJlbWFpbCI6Im1hbmFnZXJAdGVzdC5jb20iLCJpYXQiOjE3Njk4MzE5ODYsImV4cCI6MTc3MDQzNjc4Nn0.q1oHiENy2quAesjji9A-JQnyfTKDWK0F9mgUNBnrMTE


### 유저 목록 조회
GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWwxcDZ2OHAwMDAxdWM0NDhqM2MyNm1iIiwicm9sZSI6Ik1BTkFHRVIiLCJlbWFpbCI6Im1hbmFnZXJAdGVzdC5jb20iLCJpYXQiOjE3Njk4NDQ2NDgsImV4cCI6MTc2OTg0NjQ0OH0.L1dekERkjq6Ptr8jGafvc_tnq5t3CvL_GS_sLA1N4xw


### 비밀번호 변경
PATCH http://localhost:4000/api/users/setting/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWwxcDZ2OHAwMDAxdWM0NDhqM2MyNm1iIiwicm9sZSI6Ik1BTkFHRVIiLCJlbWFpbCI6Im1hbmFnZXJAdGVzdC5jb20iLCJpYXQiOjE3Njk4NDM5ODYsImV4cCI6MTc2OTg0NTc4Nn0.FDyrnPGBxRTraP4ZvK0s7zDIU3THtVN2nM4TgWHyK-c
Content-Type: application/json

{
  "password": "password123",
  "newPassword": "newPassword123"
}

### 사용자 (계정)상태 변경
PATCH http://localhost:4000/api/users/cml1p6v8p0001uc448j3c26mb/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWwyMDVoNjEwMDAwdWNrc2QwN2RqYXAzIiwicm9sZSI6IkFETUlOIiwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTc2OTg0NTI1NCwiZXhwIjoxNzY5ODQ3MDU0fQ.o8J6wCMy5uIKO0TV3SrkrED0qOVCW_yXdp3LtBqvxos
Content-Type: application/json

{
  "status": "INACTIVED"
}

### 프로젝트 생성
POST http://localhost:4000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWwxcDZ2OHAwMDAxdWM0NDhqM2MyNm1iIiwicm9sZSI6Ik1BTkFHRVIiLCJlbWFpbCI6Im1hbmFnZXJAdGVzdC5jb20iLCJpYXQiOjE3NzAwNzYwNDEsImV4cCI6MTc3MDA3Nzg0MX0.i9BdNK7bYkdXgtZ-38w0ZBM-IIi9fqw6VR58Hocj4dE
Content-Type: application/json

{
    "title": "프로젝트 포트폴리오",
    "slug": "portfolio-2026",
    "oneLine": "Next.js와 React 환경을 모두 학습 적용한 프로젝트 아카이빙 서비스입니다.",
    "description": "프로젝트 상세 설명이 들어가는 곳입니다.",
    "techs": ["React", "TypeScript", "Next.js", "Express", "Prisma" ],
    "status": "IN_PROGRESS",
    "visibility": "PUBLIC"
}

### 프로젝트 생성 (태그 10개 초과 - 에러 테스트)
POST http://localhost:4000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWwxcDZ2OHAwMDAxdWM0NDhqM2MyNm1iIiwicm9sZSI6Ik1BTkFHRVIiLCJlbWFpbCI6Im1hbmFnZXJAdGVzdC5jb20iLCJpYXQiOjE3NzAwNzc5NDUsImV4cCI6MTc3MDA3OTc0NX0.HRc9e9xiKIEp3p-jVAF8-crldLtQ35HXHbvRGT3UBq0
Content-Type: application/json

{
    "title": "프로젝트 포트폴리오",
    "slug": "portfolio-2026",
    "oneLine": "에러가 발생해야 합니다.",
    "description": "프로젝트 상세 설명이 들어가는 곳입니다.",
    "techs": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"],
    "status": "IN_PROGRESS",
    "visibility": "PUBLIC"
}

### 프로젝트 수정
PATCH http://localhost:4000/api/projects/cml5tts4p0001uc4c5qpnawzq
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWwxcDZ2OHAwMDAxdWM0NDhqM2MyNm1iIiwicm9sZSI6Ik1BTkFHRVIiLCJlbWFpbCI6Im1hbmFnZXJAdGVzdC5jb20iLCJpYXQiOjE3NzAwNzg3MzMsImV4cCI6MTc3MDA4MDUzM30.e8A0m5xXj0Yb2ONBvnt5pdDnX9lCXSiOGWNR70XZcJo
Content-Type: application/json

{
    "title": "프로젝트 아카이빙",
    "slug": "project-archiving"
}

### 프로젝트 목록
GET http://localhost:4000/api/projects/
Content-Type: application/json


### 프로젝트 최신 목록
GET http://localhost:4000/api/projects/recent
Content-Type: application/json

### 프로젝트 상세보기
GET http://localhost:4000/api/projects/cml5tts4p0001uc4c5qpnawzq
Content-Type: application/json

### 프로젝트 상세보기
PATCH http://localhost:4000/api/projects/cml5tts4p0001uc4c5qpnawzq/viewcount
Content-Type: application/json